In [2]:
import torch
import numpy as np

In [4]:
data = [[2,3],[4,5]]
tensor = torch.tensor(data,dtype=torch.float32)
print(tensor)

tensor([[2., 3.],
        [4., 5.]])


In [7]:
arr = np.arange(1,10,2)
print(type(arr))
print("simple Numpy array : ",arr)
t1 = torch.from_numpy(arr)
print(type(t1))
print("simple tensor  : ",t1)

<class 'numpy.ndarray'>
simple Numpy array :  [1 3 5 7 9]
<class 'torch.Tensor'>
simple tensor  :  tensor([1, 3, 5, 7, 9])


In [11]:
print(f"ones tensor :\n {torch.ones((2,2))}")
print(f"ones like : \n {torch.ones_like(t1)}")
print(f"random tensor : \n {torch.rand((2,3),dtype=torch.float32)}")
print(f"")

ones tensor :
 tensor([[1., 1.],
        [1., 1.]])
ones like : 
 tensor([1, 1, 1, 1, 1])
random tensor : 
 tensor([[0.8083, 0.8784, 0.3160],
        [0.6204, 0.7325, 0.7672]])


Attributes of a Tensor

In [12]:
tensor = torch.rand((2,3))
print("Datatype of Tensor : ",tensor.dtype)
print("Shape of Tensor : ",tensor.shape)
print("Device of Tensor : ",tensor.device)

Datatype of Tensor :  torch.float32
Shape of Tensor :  torch.Size([2, 3])
Device of Tensor :  cpu


Operation on tensor

In [27]:
tensor = torch.randint(low=0,high=10,size=(4,4),dtype=torch.float32)
print("Original Tensor : \n",tensor)

print("Row-1 : ",tensor[0])
print("column-1 : ",tensor[:,0] )
print("last column : ",tensor[...,-1])
print("Last row : ",tensor[-1])




Original Tensor : 
 tensor([[4., 7., 8., 9.],
        [6., 4., 8., 1.],
        [7., 6., 5., 9.],
        [1., 5., 7., 2.]])
Row-1 :  tensor([4., 7., 8., 9.])
column-1 :  tensor([4., 6., 7., 1.])
last column :  tensor([9., 1., 9., 2.])
Last row :  tensor([1., 5., 7., 2.])


In [32]:
t1 = torch.randint(1,5,(2,2))
t2 = torch.randint(6,9,(2,2))
print(f"Tensor-1 : \n {t1} \nTensor-2 : \n{t2}")
t3 = torch.cat([t1,t2],dim=1) # dim = 1 is for row and 0 is for column
print("tensor-3")
print(t3)

Tensor-1 : 
 tensor([[4, 1],
        [3, 4]]) 
Tensor-2 : 
tensor([[8, 7],
        [7, 6]])
tensor-3
tensor([[4, 1, 8, 7],
        [3, 4, 7, 6]])


In [43]:
t1 = torch.randint(1,5,(2,2),dtype=torch.float32)
t2 = torch.randint(1,5,(2,2),dtype=torch.float32)
print(f"Tensor-1 : \n{t1}")
print(f"Tensor-2 : \n{t2}")
y1 = t2 @ t1
y1 = t1.matmul(t2)
print("Matrix multiplication : \n",y1)
y2 = t1 * t2
print("Elementwise multiplication : \n",y2)

Tensor-1 : 
tensor([[1., 1.],
        [2., 1.]])
Tensor-2 : 
tensor([[4., 1.],
        [2., 1.]])
Matrix multiplication : 
 tensor([[ 6.,  2.],
        [10.,  3.]])
Elementwise multiplication : 
 tensor([[4., 1.],
        [4., 1.]])
